%YAML 1.1
---
# Snapcraft Recipe for Open Syobon Action (オープンしょぼんのアクション)
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: open-syobon-action
title: Open Syobon Action (オープンしょぼんのアクション)
summary: An open-source cross-platform port of the unforgiving Japanese platformer
description: |
  Open Syobon Action (オープンしょぼんのアクション) is an open-source cross-platform port of the unforgiving Japanese platformer using SDL.

  It is also called "Shobon no Action," "Neko Mario," "Cat Mario," or "Cat MeOUCHio."

  **Notes**

  * Rather than just playing this game by yourself, it is much more enjoyable to let someone who's never tried it before try playing the game.
  * Those who are under 12 years old are not allowed to play.
  * Please be aware that by playing this game, there is a possibility that you may develop trust issues towards other humans.
  * Please be aware that there is a possibility of getting stressed out while playing this game.
  * If any problems are caused by this game, please understand that the developers cannot take any responsibility.
  * If you wish to distribute this game to a large amount of people, please give credit to the original developer, Chiku (ちく).
  * The game's text is entirely in Japanese, but you do not need to understand the Japanese language in order to play.

  **Controls (Keyboard)**

  * Left/Right: Move
  * Z or Up: Jump
  * Space: Double-speed
  * 0 (while in-game): Self-destruction
  * Escape: Exit
  * F1: Return to title screen
  * 1-9 (while at the title screen): Select level
  * 0 at the title screen: Mystery Dungeon (there is a possibility that some bugs may occur)

  **Bugs**

  Please report any bugs at the snap's issue tracker: https://github.com/brlin-tw/OpenSyobonAction-snap/issues

  This snap is maintained by the Snapcrafters community and is not endorsed or officially maintained by the upstream developers.

  **Command Line Arguments**

  `-nosound` - Disables sound

icon: snap/gui/open-syobon-action.png
adopt-info: main

base: core18
confinement: strict
grade: stable

parts:
  # Files to patch the files in the snap
  patching:
    source: snap/local/patching
    plugin: dump
    organize:
      '*': patching/
    prime:
      - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*

  # Programs to modify the behavior of each step of the snapcraft lifecycles
  scriptlets:
    source: snap/local/scriptlets
    plugin: dump
    organize:
      '*': scriptlets/
    prime:
      - -*

  main:
    after:
      # For code patches
      - patching

      # for override-pull script
      - scriptlets

    source: https://github.com/angelXwind/OpenSyobonAction.git
    source-tag: RC3
    source-depth: 1
    override-pull: |
      set -o nounset
      "$SNAPCRAFT_STAGE/scriptlets/main-pull"

    plugin: nil
    override-build: |
      set -o nounset
      patch \
        --strip=3 \
        < "${SNAPCRAFT_STAGE}/patching/fix-linking-failure.patch"
      patch \
        --strip=3 \
        < "${SNAPCRAFT_STAGE}/patching/avoid-hardcoding-locale.patch"
      patch \
        --strip=3 \
        < "${SNAPCRAFT_STAGE}/patching/workaround-garbled-title-bar.patch"
      patch < "${SNAPCRAFT_STAGE}/patching/DxLib_manual_deadzone.patch"
      make \
        --jobs="${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      install \
        --directory \
        "${SNAPCRAFT_PART_INSTALL}/bin"
      cp \
        --recursive \
        --verbose \
        BGM \
        res \
        SE \
        SyobonAction \
        "${SNAPCRAFT_PART_INSTALL}/bin"
    build-packages:
      - libsdl-gfx1.2-dev
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl1.2-dev
    stage-packages:
      - freeglut3
      - libgl1
      - libglu1-mesa
      - libglx0
      - libpulse0
      - libsdl-gfx1.2-5
      - libsdl-image1.2
      - libsdl-mixer1.2
      - libsdl-ttf2.0-0
      - libsdl1.2debian
      - libslang2

apps:
  open-syobon-action:
    adapter: full
    command: bin/SyobonAction
    command-chain:
      - bin/open-syobon-action-launch
    extensions: [gnome-3-28]

plugs:
  # Audio output
  audio-playback:

  # Joysticks access
  joystick:
